---
title: "Poètique | Jeu"
---

# Corneille, _Trois Discours sur le poème dramatique_

<iframe src="slides/pres_poetique.html" title="description_of_embedded_content" style="width:100%; height:400px;">
  <p>Your browser does not support iframes.</p>
</iframe>
<figcaption><a href="slides/pres_poetique.html" target="_blank">Ouvrir la présentation dans une autre fenêtre</a>.</figcaption>

**18 février 2026**

## Poétique ou poétiques

Dans cette séance, nous abordons la notion de poétique théâtrale, en nous penchons notamment sur la proposition avancée par Pierre Corneille à tracer ses discours dramatiques. Comme nous avons verbalisé plusieurs fois, le XVIIe est le siècle de la formalisation et de l’institutionnalisation de différentes académies, dont l’objectif est d’encadrer les différentes disciplines, et donc de mettre en place des stratégies qui montrent l’importance et le rôle du roi, aboutissant dans l’absolutisme.

En ce qui concerne la poétique du théâtre, tout au long du siècle, nous assistons à une prolifération de théories s’appuyant presque exclusivement sur celle d’Aristote. Cela a été traduit du grec par les Italiens au XVIe siècle et parvenu en France à travers les différentes traductions, en y produisant aussi de nouvelles traductions en langue française. Parmi les grands théoriciens, nous avons l’Abbé d’Aubignac et Pierre Corneille, pourtant nous avons d’autres poétiques, qui ne constituent pas seulement des livres autonomes, mais la théorisation est menée par les auteurs au sein de leurs mêmes éditions, où on retrouve des prises de position ou des explications au sein des épîtres, des examens ou des textes adressés directement aux lecteurs.

_Pourquoi autant de poétiques?_

Tout comme toute théorie, la poétique ne fait pas l’unanimité. Par conséquent, elle peut être utilisée comme un moyen de contester ou de répondre aux critiques émises par d’autres auteurs et théoriciens. Si nous considérons les Trois discours sur le poème dramatique de Corneille, cela se positionne par rapport à la poétique de D’Aubignac, et notamment Corneille essaie de donner son interprétation des la poétique d’Aristote pour légitimer et défendre ses choix dramaturgiques. Il faut justement se souvenir que chaque théoricien affirme reprendre l’œuvre d’Aristote, mais en réalité, chacun en fournit son interprétation et sa fonction, en fonction de ses propres choix ou pour commenter, positivement ou négativement, ses contemporains.

## Corneille, _Trois Discours sur le poème dramatique_

En 1660, Pierre Corneille fait paraître une édition complète et revue de son théâtre, qui se compose de trois parties distinctes. Chacun de ces trois volumes contient un des trois discours, comme le montre la suite.

<iframe src="https://gallica.bnf.fr/ark:/12148/bpt6k1280232h/f13.item" title="Premier discours">
</iframe>
<figcaption><a href="https://catalogue.bnf.fr/ark:/12148/cb30271238n">Accès en ligne</a>.</figcaption>

<iframe src="https://gallica.bnf.fr/ark:/12148/bpt6k1280233x/f13.item" title="Deuxième discours">
</iframe>
<figcaption><a href="https://catalogue.bnf.fr/ark:/12148/cb30271238n">Accès en ligne</a>.</figcaption>

<iframe src="https://gallica.bnf.fr/ark:/12148/bpt6k12802528/f13.item" title="Troisième discours">
</iframe>
<figcaption><a href="https://catalogue.bnf.fr/ark:/12148/cb30271238n">Accès en ligne</a>.</figcaption>

Comme nous avons anticipé, Corneille aussi cite les œuvres précédentes, de l’Antiquité grecque et latine, en le mettant dans une sorte de continuité avec ses propres œuvres, seules citer de son époque. En plus, si, dans les examens précédents il partage l’idée que la distinction entre tragédie et comédie se fait sur la typologie des personnages présente, dans ce cadre, il y a un changement de perspective. Ce n’est pas tant les personnages, mais plutôt le type d’action accomplie qui change, et c’est comme ça qu’on pourrait légitimer les comédies héroïques, c’est-à-dire des comédies dont les personnages relèvent des strates plus élevées de la société.

Corneille fait preuve d’avoir lu et analysé le discours aristotélicien, mais aussi ses commentateurs, tel que Horace dans le monde latin, mais il fait aussi de rapides références à des commentateurs italiens (Robortello, Castelvetro, Beni, Pacci et Vettori). Par la suite nous allons épurer les discours pour en trahir les principes fondamentaux.

### _Discours de l'utilité et des parties du poème dramatique_

Pour lire le discours, cliquer <a href="https://theatre-classique.fr/pages/programmes/edition.php?t=../theorie/CORNEILLE_UTILITEPOEMEDRAMATIQUE.xml">ici</a>.

Le premier discours s’ouvre sur une référence directe à la poétique d’Aristote, en la mettant tout de suite face à l’autre élément fondamental : l’avis du public. Ce dernier peut s’avérer difficile à obtenir. Dans ce contexte, Corneille retrace la source de la difficulté dans le fait de considérer l’Art dramatique comme technique (de tekhnè). Autre déclaration faite tout de suite : les unités, dont on a déjà parlé et que nous allons voir plus en détail dans le troisième discours. 

> Il faut observer l'unité d'action, de lieu, et de jour, personne n'en doute ; mais ce n'est pas une petite difficulté de savoir ce que c'est que cette unité d'action, et jusques où peut s'étendre cette unité de jour et de lieu.

En rapport aux unités, Corneille note comment tout le monde dit qu’il faut les respecter en les rapportant aux maximes de vraisemblance et du nécessaire, pourtant, la première des deux est fortement critiquée par l’auteur en fonction de la tragédie. Le sujet des passions doit être repéré dans l’Histoire ou dans des préoccupations de l’Auditoire.

Concernant les théories d’Aristote et de Horace, Corneille trouve que la faille soit dans le fait que les principaux commentateurs sont des grammairiens et pas des gens de théâtre. Ce discours sert à se donner plus de légitimation, étant donné qu’il a déjà 30 ans de carrière dans cet environnement.

>  Je hasarderai quelque chose sur trente ans de travail pour la scène, et en dirai mes pensées tout simplement, sans esprit de contestation qui m'engage à les soutenir, et sans prétendre que personne renonce en ma faveur à celles qu'il en aura conçues.

Chez ces deux auteurs antiques, il repère une grosse distinction concernant l’intérêt du public. Dans Aristote on se focalise plutôt sur le sujet à travers l’agnitio et les péripéties, et non pas les mœurs. Alors que, pour Horace il faut toujours y mêler l’outil pour mieux les captiver.

_Comment le faire?_

- À travers les sentences ou des instructions tout au long de la pièce. Pourtant, il est mieux de les utiliser sobrement et rarement dans des discours généraux, dans des délibérations d’État ou d’après un homme d’importance résolu s’adressant au Roi.
- La naïve peinture des vices et vertus.
- La fin de la pièce doit inclure une punition pour les mauvaises actions, sinon le public serait laissé avec un sentiment de dégoût et d’horreur sans qu’il en retire aucun enseignement.
- La purgation des passions doit être atteinte par pitié ou par crainte.

Selon Corneille, Aristote met en scène les différents principes si bien dans la tragédie que dans la comédie, qui divergent pour typologie de personnage et d’action imitée.

Le poème dramatique doit être constitué de deux parties :

- Quantité ou extension : prologue, épisode, exode et chœurs
- partis intégraux avec les premiers constituent le corps : sujet, mœurs, sentiments, diction, musique, décor.

Comme nous avons annoncé, dans ce discours, Corneille aborde la comédie en la définissant en fonction des personnages et du sujet, c’est ainsi qu’il utilise l’épithète héroïque pour la comédie mettant en scène des princes et des rois. Dans la comédie le sujet doit être caractérisé par la résolution : les ennemis doivent devenir amis.

De manière générale, la grandeur de la pièce doit être juste, c’est-à-dire qu’elle doit posséder un commencement, un milieu et une fin. Il faudrait exclure toute action momentanée, dont on n’a pas de préparation, par exemple, dans _Horace_, nous n’avons pas de préparation à l’assassinat de Camille. En outre, Corneille souligne que la représentation ne devrait pas dépasser deux heures. Pour atteindre cet objectif, il est nécessaire de limiter le nombre de vers à environ 1500. Il convient de noter que ses pièces habituelles contiennent généralement entre 2000 et 1800 vers, respectivement pour les comédies et les tragédies, tout en cherchant à plaire au public.

Pour ce qui concerne les Mœurs, il faut qu’ils soient :

- Bonnes: selon la plupart des gens vertueux, elles sont louables, mais cela ne reflète pas la réalité de la production. Selon Corneille, « caractère brillant et élevé d’une habitude vertueuse, ou criminelle ».
- Convenables : considérer l’âge, la dignité, la naissance, l’emploi des personnages, ainsi que le pays de déroulement.
- Semblable: peinture des personnages selon l'Histoire ou la Fable.
- Égalité : conservation des mœurs des personnages tout au long de la pièce.

Pourtant, les Mœurs se déclinent en fonction aussi d’autres caractéristiques :

- Diction : suivre la grammaire et rhétorique, l’usage du vers en tant que plus élevé, et une langue nette.
- Chœurs, musique, particulièrement utile dans les pièces à machines (leur usage à restreindre).
- Décor: il est le résultat de trois arts: peinture, architecture et perspective.

La pièce est composée d’un prologue, d’un épisode et d’un épilogue, placés respectivement avant le premier chœur, au milieu et après le dernier chœur. Corneille réinterprète ces trois parties en les faisant correspondre respectivement au prologue, à l’épisode des actes centraux et à l’exode avec le dernier acte. Le prologue serait caractérisé par la présence de personnages qui ne doivent pas être présents dans le reste de la pièce. Il y aurait un seul acteur, dont la narration ne serait pas simple, mais agitée par les sentiments d’une passion. Corneille procède en présentant des prologues chez les Latins, et en réexaminant ses contemporains, il est plutôt de l’avis que le prologue antique correspondrait à la dédicace ou l’épître. Concernant l’épisode et l’exode, il faudrait que la catastrophe soit le plus tard possible. Pour ainsi faire, il faut écrire sous la passion de quelqu’un. Corneille à la fin de son premier discours, de manière circulaire revient sur le fait de reprendre le plus fidèlement possible la poétique d’Aristote.

### _Discours de la tragédie, et des moyens de la traiter selon le vraisemblable ou le nécessaire_

Pour lire le discours cliquer <a href="https://theatre-classique.fr/pages/programmes/edition.php?t=../theorie/CORNEILLE_DISCOURSDELATRAGEDIE.xml">ici</a>.

Selon Aristote, la tragédie offre une occasion d’apprendre deux compétences : maîtriser la pitié et la peur. Grâce à ces deux émotions, elle permet de purifier l’audience. La pitié est le sentiment qu’on éprouve en regardant les autres, alors que la crainte, c’est le sentiment personnel. Pour l’Italien Beni, cela reste un défi, car, s’il est vrai que la tragédie doit se concentrer sur des personnages royaux, nous, nous ressentons de l’empathie pour les gens ordinaires. Par conséquent, nous ne pouvons pas inspirer de la terreur chez le public, seulement de la compassion. Corneille convient avec Aristote sur ce point, en disant que le public est emporté à la pitié et craint par l’immedesimation.

Pour la question que nous avons avancée sur la condamnation des méchants et la récompense des bons, Corneille nous dit qu’en effet, tout cet aspect-là était entièrement absent chez les antiques. Ces deux éléments ne demeurent pas en tant qu’élément obligatoire, mais plutôt comme des détails qui mèneraient à la perfection de la pièce ; en effet, plusieurs œuvres ont eu beaucoup de succès, même en absence de l’une des deux caractéristiques, ou de toutes les deux. Il met le Cid en opposition aux autres pièces, en disant qu’il s’agit de la seule pièce où on a ces deux éléments de condamnation et de récompense. De ce décompte il faut exclure les mystères, et les pièces avec des personnes vertueuses en malheur.

La purgation repose sur la pitié et la crainte, pourtant la première ne se fait pas sans la seconde, et vice-versa. Pour la pitié il faut que les disputes, les combats, la mort se passent entre des gens liés par naissance ou par des affections, comme Horace et Curiace. Pour Aristote il y a une véritable échelle de tragédie selon le niveau de connaissance des personnages :

- on connait et on fait perir quequ'un qu'on connait;
- on ne le connaît pas, on le fait périr ;
- on ne le connaît pas, on l’a presque tué et on se reconnaît en tant que proches (représente la perfection) ;
- on connaît, on ne tue pas (condamné).

Le fait de reconnaître quelqu’un, l’agnition, est condamné par Corneille parce que chez les Italiens, elle est insérée partout, en cassant parfois les sentiments et parfois la beauté de l’œuvre.

Après, on rentre dans un discours particulièrement important, qu’on a déjà abordé, le rapport de l’auteur à l’Histoire ou de la Fable, qui, pour Corneille, ont les rapports suivants :

- quand on connaît et on tue ou on est empêché de tuer, il faut suivre l’Histoire/Fable. Cela est tellement contre nature qui est contra la vraisemblance.
- quand on ne se connaît pas, on tue et après on reconnaît qu’on est proche, ce n’est pas vraisemblable non plus, donc cela peut être inventé. La descente des dieux pour résoudre la dispute, à travers l’usage des machines, n’est pas considérée acceptable au XVIIe, mais pour les anciens, oui.
- dans le dernier cas (on connaît, on ne tue pas), on peut tout à fait inventer, puisque vraisemblable.

Aristote dit qu’il ne faut pas apporter des changements en rapport à l’Histoire/Fable, alors que Corneille parle de distinction et tempérament. Pour l’auteur il faut regarder si l’Histoire/Fable est trop cruelle ou difficile à représenter pour les spectateurs, seulement dans ce cas on est autorisé à faire des variations. Il est préférable de s’écarter de la vérité historique pour des raisons impératives, plutôt que de se conformer aveuglément aux attentes de vraisemblance. Il faut regarder à sa propre gloire et non pas aux règles du théâtre. Pourtant, chez Aristote, le rapport entre nécessaire et vraisemblable est alternativement inverti, cela pour un manque de satisfaction des deux en même temps, et donc il faut se contenter de l’un ou de l’autre.

Il y a une distinction fondamentale entre le théâtre et le roman. Le théâtre doit respecter les unités, alors que le roman doit se baser sur une extension temporelle, spatiale et d’action propre pour la compréhension du récit. Quand il faut mener un choix en termes de nécessaire ou vraisemblable, il faut mettre en place l’option qui pourrait donner plus facilement de la gloire.

Corneille introduit d'autres éléments de qualifications:

- si on suit l'Histoire, il s'agit de quelque chose de vrai;
- si on rajoute à l'Histoire, quelquefois il est vraisemblable;
- si on falsifie l'Histoire, on finit dans le nécessaire.

Ensuite, il met en rapport la vraisemblance avec la bienséance:

- la vraisemblance générale est le comportement d’un roi, la particulière est ce que fait Alexandre, donc ce qui est enseigné par l’Histoire et apporté des changements/variations engendre une falsification de l’Histoire.
- l’ordinaire est quelque chose qui arrive souvent, l’extraordinairereleve du possible, mais il est rare. Quand l’extraordinaire est vraisemblable, on est dans le domaine du vrai, si on est contre la vraisemblance, on rentre dans le domaine de la croyance qui s’explique à travers le nécessaire. 

> Je dis donc que le nécessaire, en ce qui regarde la poésie, n'est autre chose que le besoin du poète pour arriver à son but ou pour y faire arriver ses acteurs.

Parfois le poète doit "pour plaire, il a besoin quelquefois de rehausser l'éclat des belles actions et d'exténuer l'horreur des funestes.", sans pourtant

>  jamais les pousser au-delà de la vraisemblance extraordinaire, parce que ces ornements qu'il ajoute de son invention ne sont pas d'une nécessité absolue, et qu'il fait mieux de s'en passer tout à fait que d'en parer son poème contre toute sorte de vraisemblance. Pour plaire selon les règles de son art, il a besoin de renfermer son action dans l'unité de jour et de lieu ; et comme cela est d'une nécessité absolue et indispensable, il lui est beaucoup plus permis sur ces deux articles que sur celui des embellissements.

### _Discours des trois unités, d'action, de jour, et de lieu_

Pour lire le discours, cliquer <a href="https://theatre-classique.fr/pages/programmes/edition.php?t=../theorie/CORNEILLE_TROISUNITES.xml">ici</a>.

L’unité d’action dans la comédie, concerne l’unité d’intrigue, c’est-à-dire qu’il faut avoir un seul obstacle des actions des principaux auteurs ; dans la tragédie, c’est l’unité de péril, que l’héros succombe ou pas. Si on a plusieurs actions qui se passent en parallèle ou s’entremêlent, on risque de se perdre, comme quand on arrive à l’éclaircissement d’un péril et on est déjà projeté dans un autre par ex. dans Horace, la mort de Camille n’est pas nécessaire. L’unité est donc donnée par un commencement, un milieu et une fin, mais une tragédie peut aussi avoir plusieurs sous-unités, d’autant qu’elles soient subordonnées à la principale. Enfin, chaque acte doit se conclure avec le suspense pour laisser le spectateur intéressé par la suite, et seulement à la fin, tout se résolve.

Dans l’examen de La Suivante, Corneille a parlé des liens des personnages, notamment dans les termes de présence et absence des personnages sur scène et dans les discours, les personnages qui ne parlent pas ou qui sont cachés. L’action peut être divisée en deux sous-unités : nœud et dénouement. Pour Aristote le nœud est ce qui précède l’action de la pièce et elle nous est racontée au tout début ; le reste est le dénouement. Il y a une série de choses à éviter dans le dénouement : le changement des volontés et les machines. En plus, Corneille présente comme problématique quand un personnage sort et rentre sur scène plusieurs fois au sein d’un même acte, sauf si on laisse des indices de justification. Puis, il parle de « menues actions » qu’il faut marquées dans les marges pour guider les lecteurs 1. Cela parce que le spectateur voit le jeu sur scène de théâtre, alors que le lecteur a plus de mal étant tout seul dans sa lecture.

En ce qui concerne l’unité de temps, déjà Aristote dit qu’on peut excéder un peu les 24 h, Corneille dit qu’on pourrait éventuellement arriver jusqu’à un luxe temporaire de 30 h, cependant, les grands laps temporels, il faut qu’ils soient dans les intermèdes.

Pour ce qui est de l’unité de lieu, c’est assez difficile de la respecter lorsqu’on se trouve dans la chambre ou le bureau de quelqu’un, parce qu’il s’agit d’un endroit privé à laquelle tout le monde n’a pas accès. De plus, on ne devrait sourire que si la personne qui occupe cet espace est absente. Par conséquent, Corneille propose de faire correspondre l’unité de lieu à la ville, d’autant qu’on se trouve dans la même ville, tout va bien.

Il conclut son troisième discours disant qu’il n’arrive pas à trouver le respect de ces unités chez aucun des auteurs antiques et non plus chez ses contemporaines, et que les seules pièces qui respecteraient toutes ses règles seraient _Horace_, _Polyeucte_ et _Pompée_. Sa conclusion ultime définit sa personnelle interprétation des unités en tant qu’éventuelle hérésie.


**19 mars 2026**

# Initiation à la Commedia dell'Arte, par M Matilde Innocenti

<iframe src="commedia_arte.pdf" title="description_of_embedded_content" style="width:100%; height:400px;">
  <p>Your browser does not support iframes.</p>
</iframe>
<figcaption><a href="commedia_arte.pdf" target="_blank">Ouvrir la présentation dans une autre fenêtre</a>.</figcaption>


# Des Italiens au geste théâtral

<iframe src="slides/pres_jeu19.html" title="description_of_embedded_content" style="width:100%; height:400px;">
  <p>Your browser does not support iframes.</p>
</iframe>
<figcaption><a href="slides/pres_jeu19.html" target="_blank">Ouvrir la présentation dans une autre fenêtre</a>.</figcaption>

## La Comédie des Italiens

Introduite en France par les reines florentines Catherine et Marie de Médicis, la comédie italienne est particulièrement appréciée à la cour. Selon Brantôme, Catherine affectionne tout particulièrement les Zanni et les Pantalons. À travers ses types fixes, la comédie italienne est vouée à la représentation de grivoiseries, de critiques politiques et de parodies, notamment à travers une forte gestualité (musique, chant, ballet et même acrobaties).

Le rôle de la mimique est d'autant plus important qu'une bonne partie du public ne comprenait pas la langue. C'est ainsi que le geste devient une véritable traduction du texte.

Depuis le règne de Charles IX, plusieurs troupes jouent en France: à Blois et à Paris, pour le mariage d'Henri de Navarre, avec la troupe d'Alberto Ganassa en 1572; la troupe des _Golosi_ est à Blois en 1577, sous Henri III; en 1584, les _Comici Confidenti_; en 1588, les _Gelosi_ à nouveau. Entre 1600 et 1604, la troupe de Francesco Andreini joue à l'Hôtel de Bourgogne. En 1608, les _Accesi_ jouent à l'Hôtel de Bourbon, à l'Hôtel de Bourgogne et à Fontainebleau. Entre 1613 et 1618, la troupe de Tommaso Martinelli reprend également des comédies latines comme les _Menæchmi_ de Plaute. Entre 1618 et 1625, c'est au tour de la troupe de Jean-Baptiste Andreini.

Les Italiens sont déjà en concurrence avec l'Hôtel de Bourgogne. Dès 1639, la troupe de Tiberio Fiorelli s'installe à l'Hôtel Guénégaud, puis à l'Hôtel de Bourgogne lors de la création de la Comédie-Française. La concurrence était bien réelle, les Italiens ayant commencé à jouer en français également. L'année 1697 est à cet égard emblématique: après la mise en scène de _La Fausse Prude_, le roi, sous la pression de Mme de Maintenon, les chasse de Paris. La Régence, en 1716, fait à nouveau appel aux Italiens, avec la troupe de Riccoboni (dit Lelio), qui participe à la création de l'Opéra-Comique aux côtés de Marivaux et Favart.

## Lire ou jouer : tel est le dilemme

### Lecture(s)

Piot (dans Berregard, 2024), en partant de l'analyse des dédicaces, distingue deux modalités de lecture des pièces de théâtre : fictionnelle et scénique.

La lecture fictionnelle revient sur l'objet lui-même. En effet, si le livre ne contient qu'une œuvre destinée à un lecteur précis, il s'agit d'une lecture extrêmement personnelle. En revanche, dans le cas des livres miscellanés — c'est-à-dire composés de plusieurs ouvrages relevant parfois de typologies textuelles différentes, et pour cette raison aussi appelés ouvrages composites —, il s'agit plutôt d'une lecture à haute voix destinée à une collectivité.

D'autre part, la lecture scénique fait appel à l'expérience personnelle du lecteur au théâtre. Les images jouent souvent le rôle de garant de cette perspective, permettant de mieux visualiser la représentation, même dans un cadre de lecture plus personnel. On le retrouve également à travers un approfondissement de plus en plus marqué des didascalies externes, qui, dans les siècles à venir, passeront selon l'auteur de simples outils techniques à de véritables éléments poétiques, dont le style soigné sera éventuellement mis lui aussi en vers.

### Revenons à l'essence[^2]

_Qu'est-ce que c'est le théâtre?_

Gouhier, dans son ouvrage de 2002, _L'Essence du théâtre_, soutient que cette essence réside dans la représentation de la pièce. La présence d'acteurs incarnant des personnages en constitue le fondement : le personnage y occupe donc une place centrale.

_Qui est l'acteur?_

Les personnes sont caractérisées par leur capacité à exprimer leur pensée et leur personnalité. Cependant, l'acteur, en tant que personne incarnant une autre personne, abandonne sa propre personnalité pour endosser celle d'autrui : il se trouve face à une sorte de dépossession de lui-même.

L'action dramatique crée, chez l'acteur, un dédoublement s'opérant dans deux directions opposées : d'un côté, un conflit psychologique interne, entre la personne-acteur et la personne-actée, et parfois même au sein du personnage à incarner ; de l'autre, l'externalisation de cette psychologie du personnage.

L'acteur, précisément en raison de sa dimension professionnelle et de sa connaissance du jeu théâtral, est à même d'identifier les problèmes éventuels et d'apporter les modifications nécessaires en termes de jouabilité de la pièce.

_Et le texte?_

Si l'on retire l'action de la représentation théâtrale, on peut disposer d'un texte magnifique, mais on perdrait l'essence profonde du théâtre. C'est à partir de ce constat que s'opère une radicalisation menant aux origines des arts de la scène, qui étaient à l'origine pure danse, expression du mouvement du corps. Bien que Gouhier semble aller vers un refus du texte, il le requalifie de manière quasi théologique à travers une reprise implicite de l'Évangile de Jean (I, 1) : « In princípio erat Verbum ». Pourtant, ce _verbum_ est également action, constituant ainsi la co-existentialité du mot et du geste. Ce dernier porte en lui une autre contradiction, liée à la représentation : la mise en scène est contextuelle, et toutes les mises en scène postérieures n'en sont qu'un reflet.

### Le corps de l'acteur et le corps scénique

Dans la littérature, le corps humain est présenté à travers de multiples représentations, notamment par la description physique des différents personnages. Au théâtre, en revanche, le corps de l'acteur devient une matérialisation scénique de l'être humain. En tant que personnes, nous reflètons notre réalité socioculturelle (on se situe ici dans le cadre de l'anthropologie de la vie et du corps). L'art, profondément lié à son contexte de création, fournit une photographie du contexte historique d'une société et d'une culture, ainsi que de la représentation de l'homme dans ce contexte. C'est ainsi que le corps devient, dans cette perspective, à la fois sujet et objet de l'art[^3].

Dans le cadre de l'anthropologie théâtrale, on distingue trois pôles : l'auteur, l'acteur/artiste et le spectateur. Ce dernier est, à l'instar de l'artiste lui-même, actif, car il doit procéder à un acte de décodage de l'acte performatif. Cela conduit à une triple division de l'analyse : performative, mimétiste et mimésis.

> Sur la scène comme dans la société, l’individu, sur et hors scène, assimile un monde avant de le restituer sous une forme singulière.[…] L’individu dispose d’un corps, qu’il utilise notammendt dans sa communication gestuelle. (Foisil _et al_., 2016, pp.41-42)

Le geste acquiert un sens au niveau de la société tout en demeurant personnel, et évolue au fil de la vie.

Le corps est à la fois corps et instrument — dualité particulièrement complexe lorsqu'on prend en compte le travail actoral. L'acteur utilise son corps dans la vie quotidienne et lui confère de nouvelles expressions en devenant un nouveau personnage sur scène. On distingue ainsi une dualité entre corps phénoménique et corps sémiotique : l'un renvoie au simple fait d'exister, l'autre à la charge de sens que le corps peut porter.

_Quelle est le rapport entre langage et corps?_

Les premiers témoignages de langue[^4], et non de langage, parvenus jusqu'à nous sont issus de la civilisation sumérienne, bien qu'on s'accorde à penser que la langue s'est développée bien avant. D'un point de vue linguistique, anthropologique et social, la communauté scientifique s'accorde sur le fait que la langue serait née avec l'organisation sociale, l'évolution technique et la capacité d'abstraction. Le langage est, pour reprendre la terminologie précédente, essentiellement mouvement : sans le mouvement, il n'y aurait pas de langue. De même, le langage, même lorsqu'il n'est pas véhiculé par la capacité d'élocution, a comme substrat inhérent le mouvement. Pour Foisil, le texte théâtral repose sur la langue écrite et sa vocalisation; mais en l'absence de celle-ci, on revient au simple mouvement, qui est à la base des arts de la scène. Dans l'environnement théâtral, il suffit de penser à la pantomime, présente depuis l'Antiquité et reconnue en tant qu'art du spectacle aux XVII<sup>e</sup> et XIX<sup>e</sup> siècles, mais aussi au ballet, que l'on pourrait mettre en rapport, dans une perspective strictement anthropologique, avec la relation entre art et religion.

La dimension gestuelle est donc fondamentale à la représentation scénique, également en tant qu'accompagnement à la parole. L'actrice Sarah Bernhardt définit ainsi l'importance des proportions du corps et du geste théâtral :

> Par geste, l’on ne saurait entendre uniquement les mouvements des membres, mais l’ensemble de l’attitude du corps. Il faut que, dans l’artiste, tout vive à la fois, que tout exprime la sensation profonde qui l’anime, que l’œuvre il, la main, la position de la poitrine, l’inflexion de la tête contribuent à l’effet d’ensemble. […] Le côté extérieur de l’Art est parfois l’Art tout entier. (p.76)

[^1]: À ce sujet est intéressant tout le débat sur la question si le théâtre est fait pour la lecture ou pas.
[^2]: Gouhier, Henri, _L’essence du théâtre_, Librairie Philosophique J. Vrin, 2002.
[^3]: Marquetti, 2017.
[^4]: Foisil ne présente pas la distinction directe entre langue et langage, mais il serait pertinent de réintroduire dans sa réflexion la dichotomie saussurienne (Saussure, _Cours de linguistique générale_, 1916).
